version: "3.8"

services:
  nginx:
    image: docker.arvancloud.ir/nginx:1.27-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the main Nginx configuration file.
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the activated virtual host configuration files.
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      # Mount the ACME challenge webroot.
      - ./nginx/html:/usr/share/nginx/html:ro
      # Mount the Let's Encrypt certificate directory.
      - ./certbot/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  certbot:
    image: docker.arvancloud.ir/certbot/certbot
    volumes:
      # Share the persistent Let's Encrypt certificate directory.
      - ./certbot/letsencrypt:/etc/letsencrypt
      # Mount the webroot for ACME challenge responses.
      - ./nginx/html:/usr/share/nginx/html
    # This command renews certificates every 12 hours.
    entrypoint: [ "sh", "-c" ]
    command: "while true; do certbot renew; sleep 12h; done"
    restart: unless-stopped